### ISSUE TITLE
I cant get askForLocation to respond

### ISSUE THREAD

**Issue by mofman** [DaveFerger/botman-yii2-cache#2]
I can't get this to work with askForLocation am I doing something wrong? All my other questions respond properly, using this code I never get the response?

`

        $this->askForLocation('Please share your location:', function ($location) {
            $this->say('Received: '.print_r($location, true));
        }, null, [
            'message' => [
                'quick_replies' => json_encode([
                    [
                        'content_type' => 'location'
                    ]
                ])
            ]
        ]);

`

**Comment by DaveFerger** [comment]
Hy @mofman,

sorry, i forget to answer. Our project has paused now.
I create this extension from @machour class, i wanted to work with him, but he did his own repository.
[https://github.com/idk-tn/yii2-botman](url)
